import 'package:flutter/material.dart';
import 'package:analyzer_perf_test/models/generated/generated_models.dart';
import 'package:analyzer_perf_test/model_util.dart';

List<dynamic> getModels() {
  final models = List<dynamic>.empty(growable: true);  
  var model0 = Model0(
    field0: getRandomValueForField('bool'),
    field1: getRandomValueForField('Map<String, String>'),
    field2: getRandomValueForField('int'),
    field3: getRandomValueForField('List<String>'),
    field4: getRandomValueForField('DateTime'),
    field5: getRandomValueForField('List<int>'),
    field6: getRandomValueForField('List<String>'),
    field7: getRandomValueForField('Map<String, String>'),
    field8: getRandomValueForField('double'),
    field9: getRandomValueForField('bool'),
    field10: getRandomValueForField('Map<String, String>'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('double'),
    field13: getRandomValueForField('bool'),
    field14: getRandomValueForField('List<int>'),
    field15: getRandomValueForField('List<int>'),
    field16: getRandomValueForField('List<String>'),
    field17: getRandomValueForField('Map<String,int>'),
    field18: getRandomValueForField('DateTime'),
    field19: getRandomValueForField('Map<String,int>'),
    field20: getRandomValueForField('Map<String, String>'),
    field21: getRandomValueForField('Map<String,int>'),
    field22: getRandomValueForField('Map<String,int>'),
    field23: getRandomValueForField('List<String>'),
    field24: getRandomValueForField('Map<String,int>'),
    field25: getRandomValueForField('int'),
    field26: getRandomValueForField('DateTime'),
  );
  models.add(model0);
  var model1 = Model1(
    field0: getRandomValueForField('List<int>'),
    field1: getRandomValueForField('bool'),
    field2: getRandomValueForField('Map<String,int>'),
    field3: getRandomValueForField('double'),
    field4: getRandomValueForField('List<int>'),
    field5: getRandomValueForField('String'),
    field6: getRandomValueForField('DateTime'),
    field7: getRandomValueForField('DateTime'),
    field8: getRandomValueForField('List<int>'),
    field9: getRandomValueForField('Map<String,int>'),
    field10: getRandomValueForField('List<String>'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('List<int>'),
    field13: getRandomValueForField('DateTime'),
    field14: getRandomValueForField('DateTime'),
    field15: getRandomValueForField('Map<String,int>'),
    field16: getRandomValueForField('Map<String, String>'),
    field17: getRandomValueForField('double'),
    field18: getRandomValueForField('Map<String,int>'),
    field19: getRandomValueForField('double'),
    field20: getRandomValueForField('String'),
    field21: getRandomValueForField('Map<String,int>'),
    field22: getRandomValueForField('Map<String,int>'),
    field23: getRandomValueForField('List<int>'),
    field24: getRandomValueForField('List<String>'),
    field25: getRandomValueForField('List<String>'),
    field26: getRandomValueForField('Map<String,int>'),
    field27: getRandomValueForField('List<int>'),
    field28: getRandomValueForField('Map<String, String>'),
    field29: getRandomValueForField('DateTime'),
    field30: getRandomValueForField('Map<String,int>'),
    field31: getRandomValueForField('DateTime'),
    field32: getRandomValueForField('List<int>'),
    field33: getRandomValueForField('double'),
    field34: getRandomValueForField('Map<String, String>'),
    field35: getRandomValueForField('double'),
    field36: getRandomValueForField('List<String>'),
    model: model0,
  );
  models.add(model1);
  var model2 = Model2(
    field0: getRandomValueForField('Map<String, String>'),
    field1: getRandomValueForField('List<int>'),
    field2: getRandomValueForField('Map<String,int>'),
    field3: getRandomValueForField('String'),
    field4: getRandomValueForField('String'),
    field5: getRandomValueForField('DateTime'),
    field6: getRandomValueForField('bool'),
    field7: getRandomValueForField('int'),
    field8: getRandomValueForField('Map<String,int>'),
    field9: getRandomValueForField('List<int>'),
    field10: getRandomValueForField('double'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('String'),
    field13: getRandomValueForField('Map<String, String>'),
    field14: getRandomValueForField('Map<String, String>'),
    field15: getRandomValueForField('Map<String,int>'),
    field16: getRandomValueForField('List<String>'),
    field17: getRandomValueForField('int'),
    field18: getRandomValueForField('DateTime'),
    field19: getRandomValueForField('DateTime'),
    field20: getRandomValueForField('String'),
    field21: getRandomValueForField('List<int>'),
    field22: getRandomValueForField('Map<String,int>'),
    field23: getRandomValueForField('bool'),
    field24: getRandomValueForField('double'),
    field25: getRandomValueForField('bool'),
    field26: getRandomValueForField('String'),
    field27: getRandomValueForField('Map<String,int>'),
    field28: getRandomValueForField('int'),
    field29: getRandomValueForField('String'),
    field30: getRandomValueForField('double'),
    field31: getRandomValueForField('bool'),
    field32: getRandomValueForField('List<String>'),
    field33: getRandomValueForField('bool'),
    field34: getRandomValueForField('List<int>'),
    field35: getRandomValueForField('int'),
    field36: getRandomValueForField('DateTime'),
    field37: getRandomValueForField('List<int>'),
    field38: getRandomValueForField('double'),
    field39: getRandomValueForField('int'),
    field40: getRandomValueForField('double'),
    field41: getRandomValueForField('Map<String, String>'),
    field42: getRandomValueForField('int'),
    field43: getRandomValueForField('Map<String,int>'),
    field44: getRandomValueForField('int'),
    field45: getRandomValueForField('double'),
    model: model1,
  );
  models.add(model2);
  var model3 = Model3(
    field0: getRandomValueForField('DateTime'),
    field1: getRandomValueForField('int'),
    field2: getRandomValueForField('List<int>'),
    field3: getRandomValueForField('Map<String, String>'),
    field4: getRandomValueForField('String'),
    field5: getRandomValueForField('double'),
    field6: getRandomValueForField('Map<String, String>'),
    field7: getRandomValueForField('bool'),
    field8: getRandomValueForField('List<int>'),
    field9: getRandomValueForField('bool'),
    field10: getRandomValueForField('Map<String,int>'),
    field11: getRandomValueForField('Map<String, String>'),
    field12: getRandomValueForField('Map<String, String>'),
    field13: getRandomValueForField('String'),
    field14: getRandomValueForField('bool'),
    field15: getRandomValueForField('int'),
    field16: getRandomValueForField('List<int>'),
    field17: getRandomValueForField('bool'),
    field18: getRandomValueForField('DateTime'),
    field19: getRandomValueForField('List<String>'),
    field20: getRandomValueForField('int'),
    field21: getRandomValueForField('int'),
    field22: getRandomValueForField('int'),
    field23: getRandomValueForField('String'),
    field24: getRandomValueForField('List<String>'),
    field25: getRandomValueForField('bool'),
    field26: getRandomValueForField('Map<String, String>'),
    field27: getRandomValueForField('Map<String, String>'),
    field28: getRandomValueForField('Map<String,int>'),
    field29: getRandomValueForField('bool'),
    field30: getRandomValueForField('Map<String,int>'),
    field31: getRandomValueForField('int'),
    field32: getRandomValueForField('List<int>'),
    field33: getRandomValueForField('Map<String,int>'),
    field34: getRandomValueForField('String'),
    field35: getRandomValueForField('String'),
    field36: getRandomValueForField('DateTime'),
    field37: getRandomValueForField('String'),
    field38: getRandomValueForField('int'),
    field39: getRandomValueForField('Map<String,int>'),
    field40: getRandomValueForField('DateTime'),
    field41: getRandomValueForField('List<int>'),
    field42: getRandomValueForField('List<String>'),
    field43: getRandomValueForField('int'),
    field44: getRandomValueForField('List<int>'),
    field45: getRandomValueForField('double'),
    field46: getRandomValueForField('double'),
    field47: getRandomValueForField('List<String>'),
    field48: getRandomValueForField('DateTime'),
    field49: getRandomValueForField('DateTime'),
    field50: getRandomValueForField('int'),
    field51: getRandomValueForField('int'),
    field52: getRandomValueForField('int'),
    field53: getRandomValueForField('Map<String,int>'),
    field54: getRandomValueForField('DateTime'),
    field55: getRandomValueForField('Map<String,int>'),
    field56: getRandomValueForField('String'),
    field57: getRandomValueForField('Map<String,int>'),
    field58: getRandomValueForField('List<int>'),
    field59: getRandomValueForField('double'),
    field60: getRandomValueForField('DateTime'),
    field61: getRandomValueForField('Map<String, String>'),
    field62: getRandomValueForField('Map<String, String>'),
    field63: getRandomValueForField('Map<String,int>'),
    field64: getRandomValueForField('Map<String, String>'),
    field65: getRandomValueForField('bool'),
    field66: getRandomValueForField('double'),
    field67: getRandomValueForField('int'),
    field68: getRandomValueForField('DateTime'),
    field69: getRandomValueForField('List<String>'),
    field70: getRandomValueForField('Map<String,int>'),
    field71: getRandomValueForField('DateTime'),
    field72: getRandomValueForField('DateTime'),
    field73: getRandomValueForField('Map<String, String>'),
    field74: getRandomValueForField('List<String>'),
    field75: getRandomValueForField('List<int>'),
    field76: getRandomValueForField('double'),
    field77: getRandomValueForField('List<int>'),
    field78: getRandomValueForField('DateTime'),
    field79: getRandomValueForField('int'),
    field80: getRandomValueForField('String'),
    field81: getRandomValueForField('Map<String,int>'),
    field82: getRandomValueForField('bool'),
    field83: getRandomValueForField('int'),
    field84: getRandomValueForField('Map<String, String>'),
    field85: getRandomValueForField('List<String>'),
    field86: getRandomValueForField('String'),
    field87: getRandomValueForField('List<int>'),
    field88: getRandomValueForField('double'),
    field89: getRandomValueForField('List<String>'),
    field90: getRandomValueForField('List<String>'),
    field91: getRandomValueForField('List<String>'),
    field92: getRandomValueForField('List<int>'),
    model: model2,
  );
  models.add(model3);
  var model4 = Model4(
    field0: getRandomValueForField('double'),
    field1: getRandomValueForField('String'),
    field2: getRandomValueForField('Map<String, String>'),
    field3: getRandomValueForField('DateTime'),
    field4: getRandomValueForField('double'),
    field5: getRandomValueForField('Map<String,int>'),
    field6: getRandomValueForField('bool'),
    field7: getRandomValueForField('Map<String, String>'),
    field8: getRandomValueForField('Map<String, String>'),
    field9: getRandomValueForField('Map<String, String>'),
    field10: getRandomValueForField('DateTime'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('List<int>'),
    field13: getRandomValueForField('List<String>'),
    field14: getRandomValueForField('List<String>'),
    field15: getRandomValueForField('Map<String, String>'),
    field16: getRandomValueForField('double'),
    field17: getRandomValueForField('List<int>'),
    field18: getRandomValueForField('List<int>'),
    field19: getRandomValueForField('String'),
    field20: getRandomValueForField('DateTime'),
    field21: getRandomValueForField('List<String>'),
    field22: getRandomValueForField('bool'),
    field23: getRandomValueForField('double'),
    field24: getRandomValueForField('DateTime'),
    field25: getRandomValueForField('List<int>'),
    field26: getRandomValueForField('Map<String,int>'),
    field27: getRandomValueForField('Map<String, String>'),
    field28: getRandomValueForField('DateTime'),
    field29: getRandomValueForField('Map<String,int>'),
    field30: getRandomValueForField('String'),
    field31: getRandomValueForField('Map<String, String>'),
    field32: getRandomValueForField('String'),
    field33: getRandomValueForField('int'),
    field34: getRandomValueForField('int'),
    field35: getRandomValueForField('int'),
    field36: getRandomValueForField('List<String>'),
    field37: getRandomValueForField('List<String>'),
    field38: getRandomValueForField('List<String>'),
    field39: getRandomValueForField('List<String>'),
    field40: getRandomValueForField('double'),
    field41: getRandomValueForField('Map<String,int>'),
    field42: getRandomValueForField('String'),
    field43: getRandomValueForField('bool'),
    field44: getRandomValueForField('int'),
    field45: getRandomValueForField('Map<String, String>'),
    field46: getRandomValueForField('Map<String, String>'),
    field47: getRandomValueForField('int'),
    field48: getRandomValueForField('double'),
    field49: getRandomValueForField('List<String>'),
    field50: getRandomValueForField('bool'),
    field51: getRandomValueForField('List<String>'),
    field52: getRandomValueForField('bool'),
    field53: getRandomValueForField('double'),
    field54: getRandomValueForField('bool'),
    field55: getRandomValueForField('List<int>'),
    field56: getRandomValueForField('double'),
    field57: getRandomValueForField('double'),
    field58: getRandomValueForField('Map<String, String>'),
    field59: getRandomValueForField('List<int>'),
    field60: getRandomValueForField('double'),
    field61: getRandomValueForField('Map<String,int>'),
    field62: getRandomValueForField('Map<String, String>'),
    field63: getRandomValueForField('List<String>'),
    field64: getRandomValueForField('List<String>'),
    field65: getRandomValueForField('Map<String,int>'),
    field66: getRandomValueForField('double'),
    field67: getRandomValueForField('double'),
    field68: getRandomValueForField('Map<String,int>'),
    field69: getRandomValueForField('Map<String, String>'),
    field70: getRandomValueForField('bool'),
    field71: getRandomValueForField('List<String>'),
    field72: getRandomValueForField('double'),
    field73: getRandomValueForField('List<String>'),
    field74: getRandomValueForField('DateTime'),
    field75: getRandomValueForField('List<int>'),
    field76: getRandomValueForField('List<int>'),
    field77: getRandomValueForField('double'),
    field78: getRandomValueForField('String'),
    field79: getRandomValueForField('List<int>'),
    field80: getRandomValueForField('Map<String,int>'),
    field81: getRandomValueForField('Map<String, String>'),
    field82: getRandomValueForField('List<int>'),
    field83: getRandomValueForField('bool'),
    field84: getRandomValueForField('double'),
    field85: getRandomValueForField('List<String>'),
    field86: getRandomValueForField('String'),
    field87: getRandomValueForField('String'),
    field88: getRandomValueForField('Map<String,int>'),
    field89: getRandomValueForField('List<String>'),
    model: model3,
  );
  models.add(model4);
  var model5 = Model5(
    field0: getRandomValueForField('bool'),
    field1: getRandomValueForField('Map<String, String>'),
    field2: getRandomValueForField('String'),
    field3: getRandomValueForField('int'),
    field4: getRandomValueForField('List<int>'),
    field5: getRandomValueForField('bool'),
    field6: getRandomValueForField('double'),
    field7: getRandomValueForField('DateTime'),
    field8: getRandomValueForField('Map<String,int>'),
    field9: getRandomValueForField('List<int>'),
    field10: getRandomValueForField('double'),
    field11: getRandomValueForField('Map<String, String>'),
    field12: getRandomValueForField('int'),
    field13: getRandomValueForField('Map<String,int>'),
    field14: getRandomValueForField('double'),
    field15: getRandomValueForField('bool'),
    field16: getRandomValueForField('int'),
    field17: getRandomValueForField('Map<String, String>'),
    field18: getRandomValueForField('List<int>'),
    field19: getRandomValueForField('List<String>'),
    field20: getRandomValueForField('DateTime'),
    field21: getRandomValueForField('List<String>'),
    field22: getRandomValueForField('int'),
    field23: getRandomValueForField('List<int>'),
    field24: getRandomValueForField('int'),
    field25: getRandomValueForField('List<String>'),
    field26: getRandomValueForField('List<int>'),
    field27: getRandomValueForField('String'),
    field28: getRandomValueForField('bool'),
    field29: getRandomValueForField('double'),
    field30: getRandomValueForField('String'),
    field31: getRandomValueForField('Map<String, String>'),
    field32: getRandomValueForField('int'),
    field33: getRandomValueForField('List<String>'),
    field34: getRandomValueForField('bool'),
    field35: getRandomValueForField('String'),
    field36: getRandomValueForField('List<String>'),
    field37: getRandomValueForField('int'),
    field38: getRandomValueForField('String'),
    field39: getRandomValueForField('double'),
    field40: getRandomValueForField('DateTime'),
    field41: getRandomValueForField('String'),
    field42: getRandomValueForField('Map<String,int>'),
    field43: getRandomValueForField('DateTime'),
    field44: getRandomValueForField('bool'),
    field45: getRandomValueForField('String'),
    field46: getRandomValueForField('String'),
    field47: getRandomValueForField('Map<String,int>'),
    field48: getRandomValueForField('Map<String,int>'),
    field49: getRandomValueForField('DateTime'),
    field50: getRandomValueForField('List<int>'),
    field51: getRandomValueForField('Map<String,int>'),
    field52: getRandomValueForField('Map<String,int>'),
    field53: getRandomValueForField('bool'),
    field54: getRandomValueForField('double'),
    field55: getRandomValueForField('bool'),
    field56: getRandomValueForField('double'),
    field57: getRandomValueForField('Map<String,int>'),
    field58: getRandomValueForField('List<int>'),
    field59: getRandomValueForField('Map<String, String>'),
    field60: getRandomValueForField('String'),
    field61: getRandomValueForField('double'),
    field62: getRandomValueForField('List<String>'),
    field63: getRandomValueForField('Map<String,int>'),
    field64: getRandomValueForField('Map<String, String>'),
    field65: getRandomValueForField('List<int>'),
    field66: getRandomValueForField('int'),
    field67: getRandomValueForField('int'),
    field68: getRandomValueForField('int'),
    field69: getRandomValueForField('Map<String, String>'),
    field70: getRandomValueForField('bool'),
    field71: getRandomValueForField('String'),
    field72: getRandomValueForField('int'),
    field73: getRandomValueForField('Map<String,int>'),
    field74: getRandomValueForField('Map<String, String>'),
    field75: getRandomValueForField('Map<String,int>'),
    field76: getRandomValueForField('Map<String,int>'),
    field77: getRandomValueForField('Map<String, String>'),
    field78: getRandomValueForField('int'),
    model: model4,
  );
  models.add(model5);
  var model6 = Model6(
    field0: getRandomValueForField('bool'),
    field1: getRandomValueForField('Map<String, String>'),
    field2: getRandomValueForField('String'),
    field3: getRandomValueForField('int'),
    field4: getRandomValueForField('List<int>'),
    field5: getRandomValueForField('bool'),
    field6: getRandomValueForField('double'),
    field7: getRandomValueForField('DateTime'),
    field8: getRandomValueForField('Map<String,int>'),
    field9: getRandomValueForField('List<int>'),
    field10: getRandomValueForField('double'),
    field11: getRandomValueForField('Map<String, String>'),
    field12: getRandomValueForField('int'),
    field13: getRandomValueForField('Map<String,int>'),
    field14: getRandomValueForField('double'),
    field15: getRandomValueForField('bool'),
    field16: getRandomValueForField('int'),
    field17: getRandomValueForField('Map<String, String>'),
    field18: getRandomValueForField('List<int>'),
    field19: getRandomValueForField('List<String>'),
    field20: getRandomValueForField('DateTime'),
    field21: getRandomValueForField('List<String>'),
    field22: getRandomValueForField('int'),
    field23: getRandomValueForField('List<int>'),
    field24: getRandomValueForField('int'),
    field25: getRandomValueForField('List<String>'),
    field26: getRandomValueForField('List<int>'),
    field27: getRandomValueForField('String'),
    field28: getRandomValueForField('bool'),
    field29: getRandomValueForField('double'),
    field30: getRandomValueForField('String'),
    field31: getRandomValueForField('Map<String, String>'),
    field32: getRandomValueForField('int'),
    field33: getRandomValueForField('List<String>'),
    field34: getRandomValueForField('bool'),
    field35: getRandomValueForField('String'),
    field36: getRandomValueForField('List<String>'),
    field37: getRandomValueForField('int'),
    field38: getRandomValueForField('String'),
    field39: getRandomValueForField('double'),
    field40: getRandomValueForField('DateTime'),
    field41: getRandomValueForField('String'),
    field42: getRandomValueForField('Map<String,int>'),
    field43: getRandomValueForField('DateTime'),
    field44: getRandomValueForField('bool'),
    field45: getRandomValueForField('String'),
    field46: getRandomValueForField('String'),
    field47: getRandomValueForField('Map<String,int>'),
    field48: getRandomValueForField('Map<String,int>'),
    field49: getRandomValueForField('DateTime'),
    field50: getRandomValueForField('List<int>'),
    field51: getRandomValueForField('Map<String,int>'),
    field52: getRandomValueForField('Map<String,int>'),
    field53: getRandomValueForField('bool'),
    field54: getRandomValueForField('double'),
    field55: getRandomValueForField('bool'),
    field56: getRandomValueForField('double'),
    field57: getRandomValueForField('Map<String,int>'),
    field58: getRandomValueForField('List<int>'),
    field59: getRandomValueForField('Map<String, String>'),
    field60: getRandomValueForField('String'),
    field61: getRandomValueForField('double'),
    field62: getRandomValueForField('List<String>'),
    field63: getRandomValueForField('Map<String,int>'),
    field64: getRandomValueForField('Map<String, String>'),
    field65: getRandomValueForField('List<int>'),
    field66: getRandomValueForField('int'),
    field67: getRandomValueForField('int'),
    field68: getRandomValueForField('int'),
    field69: getRandomValueForField('Map<String, String>'),
    field70: getRandomValueForField('bool'),
    field71: getRandomValueForField('String'),
    field72: getRandomValueForField('int'),
    field73: getRandomValueForField('Map<String,int>'),
    field74: getRandomValueForField('Map<String, String>'),
    field75: getRandomValueForField('Map<String,int>'),
    field76: getRandomValueForField('Map<String,int>'),
    field77: getRandomValueForField('Map<String, String>'),
    field78: getRandomValueForField('int'),
    model: model5,
  );
  models.add(model6);
  var model7 = Model7(
    field0: getRandomValueForField('Map<String, String>'),
    field1: getRandomValueForField('Map<String, String>'),
    field2: getRandomValueForField('bool'),
    field3: getRandomValueForField('List<String>'),
    field4: getRandomValueForField('bool'),
    field5: getRandomValueForField('DateTime'),
    field6: getRandomValueForField('Map<String, String>'),
    field7: getRandomValueForField('Map<String,int>'),
    field8: getRandomValueForField('bool'),
    field9: getRandomValueForField('List<String>'),
    field10: getRandomValueForField('bool'),
    field11: getRandomValueForField('DateTime'),
    field12: getRandomValueForField('int'),
    field13: getRandomValueForField('DateTime'),
    field14: getRandomValueForField('Map<String, String>'),
    field15: getRandomValueForField('DateTime'),
    field16: getRandomValueForField('DateTime'),
    field17: getRandomValueForField('DateTime'),
    field18: getRandomValueForField('double'),
    field19: getRandomValueForField('DateTime'),
    field20: getRandomValueForField('List<String>'),
    field21: getRandomValueForField('String'),
    field22: getRandomValueForField('List<String>'),
    field23: getRandomValueForField('String'),
    model: model6,
  );
  models.add(model7);
  var model8 = Model8(
    field0: getRandomValueForField('String'),
    field1: getRandomValueForField('double'),
    field2: getRandomValueForField('Map<String, String>'),
    field3: getRandomValueForField('bool'),
    field4: getRandomValueForField('bool'),
    field5: getRandomValueForField('double'),
    field6: getRandomValueForField('List<String>'),
    field7: getRandomValueForField('List<String>'),
    field8: getRandomValueForField('String'),
    field9: getRandomValueForField('String'),
    field10: getRandomValueForField('List<int>'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('bool'),
    field13: getRandomValueForField('List<int>'),
    field14: getRandomValueForField('double'),
    field15: getRandomValueForField('String'),
    field16: getRandomValueForField('DateTime'),
    field17: getRandomValueForField('double'),
    field18: getRandomValueForField('DateTime'),
    field19: getRandomValueForField('DateTime'),
    field20: getRandomValueForField('bool'),
    field21: getRandomValueForField('double'),
    field22: getRandomValueForField('DateTime'),
    field23: getRandomValueForField('String'),
    field24: getRandomValueForField('double'),
    field25: getRandomValueForField('List<int>'),
    field26: getRandomValueForField('String'),
    field27: getRandomValueForField('List<int>'),
    field28: getRandomValueForField('double'),
    field29: getRandomValueForField('Map<String, String>'),
    field30: getRandomValueForField('Map<String, String>'),
    field31: getRandomValueForField('Map<String,int>'),
    field32: getRandomValueForField('Map<String, String>'),
    field33: getRandomValueForField('bool'),
    field34: getRandomValueForField('String'),
    field35: getRandomValueForField('DateTime'),
    field36: getRandomValueForField('int'),
    field37: getRandomValueForField('List<int>'),
    field38: getRandomValueForField('Map<String,int>'),
    field39: getRandomValueForField('double'),
    field40: getRandomValueForField('bool'),
    field41: getRandomValueForField('DateTime'),
    field42: getRandomValueForField('Map<String,int>'),
    field43: getRandomValueForField('Map<String,int>'),
    field44: getRandomValueForField('int'),
    field45: getRandomValueForField('List<String>'),
    field46: getRandomValueForField('List<String>'),
    field47: getRandomValueForField('List<int>'),
    field48: getRandomValueForField('int'),
    field49: getRandomValueForField('Map<String,int>'),
    field50: getRandomValueForField('List<String>'),
    field51: getRandomValueForField('DateTime'),
    field52: getRandomValueForField('double'),
    field53: getRandomValueForField('DateTime'),
    field54: getRandomValueForField('double'),
    field55: getRandomValueForField('bool'),
    field56: getRandomValueForField('Map<String,int>'),
    field57: getRandomValueForField('double'),
    field58: getRandomValueForField('DateTime'),
    field59: getRandomValueForField('bool'),
    field60: getRandomValueForField('bool'),
    field61: getRandomValueForField('List<String>'),
    field62: getRandomValueForField('List<int>'),
    field63: getRandomValueForField('String'),
    field64: getRandomValueForField('bool'),
    field65: getRandomValueForField('List<int>'),
    field66: getRandomValueForField('Map<String,int>'),
    field67: getRandomValueForField('Map<String, String>'),
    field68: getRandomValueForField('int'),
    field69: getRandomValueForField('int'),
    field70: getRandomValueForField('int'),
    field71: getRandomValueForField('double'),
    field72: getRandomValueForField('List<String>'),
    field73: getRandomValueForField('Map<String,int>'),
    field74: getRandomValueForField('List<int>'),
    field75: getRandomValueForField('bool'),
    field76: getRandomValueForField('List<int>'),
    field77: getRandomValueForField('DateTime'),
    field78: getRandomValueForField('Map<String, String>'),
    field79: getRandomValueForField('List<int>'),
    field80: getRandomValueForField('List<String>'),
    field81: getRandomValueForField('double'),
    field82: getRandomValueForField('int'),
    field83: getRandomValueForField('List<int>'),
    field84: getRandomValueForField('DateTime'),
    field85: getRandomValueForField('DateTime'),
    field86: getRandomValueForField('DateTime'),
    model: model7,
  );
  models.add(model8);
  var model9 = Model9(
    field0: getRandomValueForField('String'),
    field1: getRandomValueForField('double'),
    field2: getRandomValueForField('Map<String, String>'),
    field3: getRandomValueForField('bool'),
    field4: getRandomValueForField('bool'),
    field5: getRandomValueForField('double'),
    field6: getRandomValueForField('List<String>'),
    field7: getRandomValueForField('List<String>'),
    field8: getRandomValueForField('String'),
    field9: getRandomValueForField('String'),
    field10: getRandomValueForField('List<int>'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('bool'),
    field13: getRandomValueForField('List<int>'),
    field14: getRandomValueForField('double'),
    field15: getRandomValueForField('String'),
    field16: getRandomValueForField('DateTime'),
    field17: getRandomValueForField('double'),
    field18: getRandomValueForField('DateTime'),
    field19: getRandomValueForField('DateTime'),
    field20: getRandomValueForField('bool'),
    field21: getRandomValueForField('double'),
    field22: getRandomValueForField('DateTime'),
    field23: getRandomValueForField('String'),
    field24: getRandomValueForField('double'),
    field25: getRandomValueForField('List<int>'),
    field26: getRandomValueForField('String'),
    field27: getRandomValueForField('List<int>'),
    field28: getRandomValueForField('double'),
    field29: getRandomValueForField('Map<String, String>'),
    field30: getRandomValueForField('Map<String, String>'),
    field31: getRandomValueForField('Map<String,int>'),
    field32: getRandomValueForField('Map<String, String>'),
    field33: getRandomValueForField('bool'),
    field34: getRandomValueForField('String'),
    field35: getRandomValueForField('DateTime'),
    field36: getRandomValueForField('int'),
    field37: getRandomValueForField('List<int>'),
    field38: getRandomValueForField('Map<String,int>'),
    field39: getRandomValueForField('double'),
    field40: getRandomValueForField('bool'),
    field41: getRandomValueForField('DateTime'),
    field42: getRandomValueForField('Map<String,int>'),
    field43: getRandomValueForField('Map<String,int>'),
    field44: getRandomValueForField('int'),
    field45: getRandomValueForField('List<String>'),
    field46: getRandomValueForField('List<String>'),
    field47: getRandomValueForField('List<int>'),
    field48: getRandomValueForField('int'),
    field49: getRandomValueForField('Map<String,int>'),
    field50: getRandomValueForField('List<String>'),
    field51: getRandomValueForField('DateTime'),
    field52: getRandomValueForField('double'),
    field53: getRandomValueForField('DateTime'),
    field54: getRandomValueForField('double'),
    field55: getRandomValueForField('bool'),
    field56: getRandomValueForField('Map<String,int>'),
    field57: getRandomValueForField('double'),
    field58: getRandomValueForField('DateTime'),
    field59: getRandomValueForField('bool'),
    field60: getRandomValueForField('bool'),
    field61: getRandomValueForField('List<String>'),
    field62: getRandomValueForField('List<int>'),
    field63: getRandomValueForField('String'),
    field64: getRandomValueForField('bool'),
    field65: getRandomValueForField('List<int>'),
    field66: getRandomValueForField('Map<String,int>'),
    field67: getRandomValueForField('Map<String, String>'),
    field68: getRandomValueForField('int'),
    field69: getRandomValueForField('int'),
    field70: getRandomValueForField('int'),
    field71: getRandomValueForField('double'),
    field72: getRandomValueForField('List<String>'),
    field73: getRandomValueForField('Map<String,int>'),
    field74: getRandomValueForField('List<int>'),
    field75: getRandomValueForField('bool'),
    field76: getRandomValueForField('List<int>'),
    field77: getRandomValueForField('DateTime'),
    field78: getRandomValueForField('Map<String, String>'),
    field79: getRandomValueForField('List<int>'),
    field80: getRandomValueForField('List<String>'),
    field81: getRandomValueForField('double'),
    field82: getRandomValueForField('int'),
    field83: getRandomValueForField('List<int>'),
    field84: getRandomValueForField('DateTime'),
    field85: getRandomValueForField('DateTime'),
    field86: getRandomValueForField('DateTime'),
    model: model8,
  );
  models.add(model9);
  return models;
}


class ModelViewer extends StatelessWidget {
  final List<dynamic> models;

  const ModelViewer({super.key, required this.models});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Model Viewer'),
      ),
      body: ListView.builder(
        itemCount: models.length,
        itemBuilder: (context, index) {
          final model = models[index];
          return ListTile(
            title: Text(model.runtimeType.toString()),
            subtitle: Text(
              // Display the first 3 fields (or less if there are fewer)
              model.toString(),
            ),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) =>
                      DetailPage(model: model), // Pass the model
                ),
              );
            },
          );
        },
      ),
    );
  }
}

class DetailPage extends StatelessWidget {
  final dynamic model;

  const DetailPage({super.key, required this.model});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Detail View - ${model.runtimeType}'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Text(model.toString()), // Display all fields
      ),
    );
  }
}

void main() {
  final models = getModels();
  runApp(MaterialApp(
    home: ModelViewer(models: models),
  ));
}
