import 'package:flutter/material.dart';
import 'package:analyzer_perf_test/models/generated/generated_models.dart';
import 'package:analyzer_perf_test/model_util.dart';

List<dynamic> getModels() {
  final models = List<dynamic>.empty(growable: true);  
  var model0 = Model0(
    field0: getRandomValueForField('String'),
    field1: getRandomValueForField('Map<String,int>'),
    field2: getRandomValueForField('bool'),
    field3: getRandomValueForField('int'),
    field4: getRandomValueForField('DateTime'),
    field5: getRandomValueForField('List<String>'),
    field6: getRandomValueForField('bool'),
    field7: getRandomValueForField('double'),
    field8: getRandomValueForField('String'),
    field9: getRandomValueForField('Map<String,int>'),
    field10: getRandomValueForField('DateTime'),
    field11: getRandomValueForField('List<int>'),
    field12: getRandomValueForField('String'),
    field13: getRandomValueForField('int'),
    field14: getRandomValueForField('Map<String,int>'),
    field15: getRandomValueForField('Map<String,int>'),
    field16: getRandomValueForField('DateTime'),
    field17: getRandomValueForField('bool'),
    field18: getRandomValueForField('List<String>'),
    field19: getRandomValueForField('Map<String, String>'),
    field20: getRandomValueForField('DateTime'),
    field21: getRandomValueForField('int'),
    field22: getRandomValueForField('List<int>'),
    field23: getRandomValueForField('List<int>'),
    field24: getRandomValueForField('int'),
    field25: getRandomValueForField('Map<String, String>'),
    field26: getRandomValueForField('Map<String,int>'),
    field27: getRandomValueForField('String'),
    field28: getRandomValueForField('Map<String, String>'),
    field29: getRandomValueForField('Map<String, String>'),
    field30: getRandomValueForField('bool'),
    field31: getRandomValueForField('int'),
    field32: getRandomValueForField('List<String>'),
    field33: getRandomValueForField('List<String>'),
    field34: getRandomValueForField('List<int>'),
    field35: getRandomValueForField('int'),
    field36: getRandomValueForField('List<String>'),
    field37: getRandomValueForField('int'),
    field38: getRandomValueForField('List<int>'),
    field39: getRandomValueForField('DateTime'),
    field40: getRandomValueForField('bool'),
    field41: getRandomValueForField('List<String>'),
    field42: getRandomValueForField('DateTime'),
    field43: getRandomValueForField('Map<String, String>'),
    field44: getRandomValueForField('List<String>'),
    field45: getRandomValueForField('List<String>'),
    field46: getRandomValueForField('List<String>'),
    field47: getRandomValueForField('String'),
    field48: getRandomValueForField('DateTime'),
    field49: getRandomValueForField('bool'),
  );
  models.add(model0);
  var model1 = Model1(
    field0: getRandomValueForField('String'),
    field1: getRandomValueForField('bool'),
    field2: getRandomValueForField('DateTime'),
    field3: getRandomValueForField('Map<String, String>'),
    field4: getRandomValueForField('bool'),
    field5: getRandomValueForField('double'),
    field6: getRandomValueForField('DateTime'),
    field7: getRandomValueForField('Map<String, String>'),
    field8: getRandomValueForField('List<String>'),
    field9: getRandomValueForField('DateTime'),
    field10: getRandomValueForField('bool'),
    field11: getRandomValueForField('DateTime'),
    field12: getRandomValueForField('DateTime'),
    field13: getRandomValueForField('bool'),
    field14: getRandomValueForField('bool'),
    field15: getRandomValueForField('String'),
    field16: getRandomValueForField('double'),
    field17: getRandomValueForField('Map<String, String>'),
    field18: getRandomValueForField('String'),
    field19: getRandomValueForField('String'),
    field20: getRandomValueForField('Map<String,int>'),
    field21: getRandomValueForField('List<String>'),
    field22: getRandomValueForField('Map<String,int>'),
    field23: getRandomValueForField('int'),
    field24: getRandomValueForField('double'),
    field25: getRandomValueForField('String'),
    field26: getRandomValueForField('int'),
    field27: getRandomValueForField('DateTime'),
    field28: getRandomValueForField('Map<String, String>'),
    field29: getRandomValueForField('Map<String,int>'),
    field30: getRandomValueForField('List<String>'),
    field31: getRandomValueForField('Map<String,int>'),
    field32: getRandomValueForField('double'),
    field33: getRandomValueForField('List<String>'),
    field34: getRandomValueForField('String'),
    field35: getRandomValueForField('double'),
    field36: getRandomValueForField('List<String>'),
    field37: getRandomValueForField('double'),
    field38: getRandomValueForField('Map<String,int>'),
    field39: getRandomValueForField('String'),
    field40: getRandomValueForField('DateTime'),
    field41: getRandomValueForField('List<String>'),
    field42: getRandomValueForField('String'),
    field43: getRandomValueForField('String'),
    field44: getRandomValueForField('String'),
    field45: getRandomValueForField('double'),
    field46: getRandomValueForField('bool'),
    field47: getRandomValueForField('bool'),
    field48: getRandomValueForField('Map<String,int>'),
    field49: getRandomValueForField('int'),
    model: model0,
  );
  models.add(model1);
  var model2 = Model2(
    field0: getRandomValueForField('Map<String,int>'),
    field1: getRandomValueForField('Map<String,int>'),
    field2: getRandomValueForField('Map<String, String>'),
    field3: getRandomValueForField('Map<String,int>'),
    field4: getRandomValueForField('Map<String,int>'),
    field5: getRandomValueForField('Map<String, String>'),
    field6: getRandomValueForField('int'),
    field7: getRandomValueForField('bool'),
    field8: getRandomValueForField('DateTime'),
    field9: getRandomValueForField('String'),
    field10: getRandomValueForField('double'),
    field11: getRandomValueForField('Map<String, String>'),
    field12: getRandomValueForField('List<String>'),
    field13: getRandomValueForField('Map<String,int>'),
    field14: getRandomValueForField('Map<String,int>'),
    field15: getRandomValueForField('List<String>'),
    field16: getRandomValueForField('DateTime'),
    field17: getRandomValueForField('DateTime'),
    field18: getRandomValueForField('List<int>'),
    field19: getRandomValueForField('double'),
    field20: getRandomValueForField('String'),
    field21: getRandomValueForField('Map<String, String>'),
    field22: getRandomValueForField('Map<String, String>'),
    field23: getRandomValueForField('DateTime'),
    field24: getRandomValueForField('int'),
    field25: getRandomValueForField('bool'),
    field26: getRandomValueForField('DateTime'),
    field27: getRandomValueForField('Map<String, String>'),
    field28: getRandomValueForField('List<String>'),
    field29: getRandomValueForField('List<String>'),
    field30: getRandomValueForField('double'),
    field31: getRandomValueForField('double'),
    field32: getRandomValueForField('Map<String,int>'),
    field33: getRandomValueForField('List<int>'),
    field34: getRandomValueForField('bool'),
    field35: getRandomValueForField('Map<String, String>'),
    field36: getRandomValueForField('List<int>'),
    field37: getRandomValueForField('Map<String, String>'),
    field38: getRandomValueForField('String'),
    field39: getRandomValueForField('Map<String, String>'),
    field40: getRandomValueForField('Map<String, String>'),
    field41: getRandomValueForField('bool'),
    field42: getRandomValueForField('List<int>'),
    field43: getRandomValueForField('DateTime'),
    field44: getRandomValueForField('List<String>'),
    field45: getRandomValueForField('Map<String, String>'),
    field46: getRandomValueForField('int'),
    field47: getRandomValueForField('String'),
    field48: getRandomValueForField('List<String>'),
    field49: getRandomValueForField('Map<String, String>'),
    model: model1,
  );
  models.add(model2);
  var model3 = Model3(
    field0: getRandomValueForField('Map<String,int>'),
    field1: getRandomValueForField('Map<String,int>'),
    field2: getRandomValueForField('Map<String, String>'),
    field3: getRandomValueForField('Map<String,int>'),
    field4: getRandomValueForField('Map<String,int>'),
    field5: getRandomValueForField('Map<String, String>'),
    field6: getRandomValueForField('int'),
    field7: getRandomValueForField('bool'),
    field8: getRandomValueForField('DateTime'),
    field9: getRandomValueForField('String'),
    field10: getRandomValueForField('double'),
    field11: getRandomValueForField('Map<String, String>'),
    field12: getRandomValueForField('List<String>'),
    field13: getRandomValueForField('Map<String,int>'),
    field14: getRandomValueForField('Map<String,int>'),
    field15: getRandomValueForField('List<String>'),
    field16: getRandomValueForField('DateTime'),
    field17: getRandomValueForField('DateTime'),
    field18: getRandomValueForField('List<int>'),
    field19: getRandomValueForField('double'),
    field20: getRandomValueForField('String'),
    field21: getRandomValueForField('Map<String, String>'),
    field22: getRandomValueForField('Map<String, String>'),
    field23: getRandomValueForField('DateTime'),
    field24: getRandomValueForField('int'),
    field25: getRandomValueForField('bool'),
    field26: getRandomValueForField('DateTime'),
    field27: getRandomValueForField('Map<String, String>'),
    field28: getRandomValueForField('List<String>'),
    field29: getRandomValueForField('List<String>'),
    field30: getRandomValueForField('double'),
    field31: getRandomValueForField('double'),
    field32: getRandomValueForField('Map<String,int>'),
    field33: getRandomValueForField('List<int>'),
    field34: getRandomValueForField('bool'),
    field35: getRandomValueForField('Map<String, String>'),
    field36: getRandomValueForField('List<int>'),
    field37: getRandomValueForField('Map<String, String>'),
    field38: getRandomValueForField('String'),
    field39: getRandomValueForField('Map<String, String>'),
    field40: getRandomValueForField('Map<String, String>'),
    field41: getRandomValueForField('bool'),
    field42: getRandomValueForField('List<int>'),
    field43: getRandomValueForField('DateTime'),
    field44: getRandomValueForField('List<String>'),
    field45: getRandomValueForField('Map<String, String>'),
    field46: getRandomValueForField('int'),
    field47: getRandomValueForField('String'),
    field48: getRandomValueForField('List<String>'),
    field49: getRandomValueForField('Map<String, String>'),
    model: model2,
  );
  models.add(model3);
  var model4 = Model4(
    field0: getRandomValueForField('String'),
    field1: getRandomValueForField('List<String>'),
    field2: getRandomValueForField('List<String>'),
    field3: getRandomValueForField('String'),
    field4: getRandomValueForField('double'),
    field5: getRandomValueForField('List<int>'),
    field6: getRandomValueForField('int'),
    field7: getRandomValueForField('List<int>'),
    field8: getRandomValueForField('int'),
    field9: getRandomValueForField('String'),
    field10: getRandomValueForField('bool'),
    field11: getRandomValueForField('double'),
    field12: getRandomValueForField('Map<String, String>'),
    field13: getRandomValueForField('List<int>'),
    field14: getRandomValueForField('bool'),
    field15: getRandomValueForField('DateTime'),
    field16: getRandomValueForField('Map<String, String>'),
    field17: getRandomValueForField('bool'),
    field18: getRandomValueForField('Map<String, String>'),
    field19: getRandomValueForField('double'),
    field20: getRandomValueForField('Map<String, String>'),
    field21: getRandomValueForField('String'),
    field22: getRandomValueForField('bool'),
    field23: getRandomValueForField('bool'),
    field24: getRandomValueForField('String'),
    field25: getRandomValueForField('DateTime'),
    field26: getRandomValueForField('String'),
    field27: getRandomValueForField('Map<String, String>'),
    field28: getRandomValueForField('String'),
    field29: getRandomValueForField('List<int>'),
    field30: getRandomValueForField('Map<String,int>'),
    field31: getRandomValueForField('bool'),
    field32: getRandomValueForField('List<String>'),
    field33: getRandomValueForField('Map<String,int>'),
    field34: getRandomValueForField('List<int>'),
    field35: getRandomValueForField('double'),
    field36: getRandomValueForField('List<String>'),
    field37: getRandomValueForField('Map<String, String>'),
    field38: getRandomValueForField('bool'),
    field39: getRandomValueForField('int'),
    field40: getRandomValueForField('List<int>'),
    field41: getRandomValueForField('Map<String, String>'),
    field42: getRandomValueForField('DateTime'),
    field43: getRandomValueForField('int'),
    field44: getRandomValueForField('List<String>'),
    field45: getRandomValueForField('bool'),
    field46: getRandomValueForField('DateTime'),
    field47: getRandomValueForField('List<int>'),
    field48: getRandomValueForField('List<String>'),
    field49: getRandomValueForField('int'),
    model: model3,
  );
  models.add(model4);
  var model5 = Model5(
    field0: getRandomValueForField('String'),
    field1: getRandomValueForField('List<String>'),
    field2: getRandomValueForField('List<String>'),
    field3: getRandomValueForField('String'),
    field4: getRandomValueForField('double'),
    field5: getRandomValueForField('List<int>'),
    field6: getRandomValueForField('int'),
    field7: getRandomValueForField('List<int>'),
    field8: getRandomValueForField('int'),
    field9: getRandomValueForField('String'),
    field10: getRandomValueForField('bool'),
    field11: getRandomValueForField('double'),
    field12: getRandomValueForField('Map<String, String>'),
    field13: getRandomValueForField('List<int>'),
    field14: getRandomValueForField('bool'),
    field15: getRandomValueForField('DateTime'),
    field16: getRandomValueForField('Map<String, String>'),
    field17: getRandomValueForField('bool'),
    field18: getRandomValueForField('Map<String, String>'),
    field19: getRandomValueForField('double'),
    field20: getRandomValueForField('Map<String, String>'),
    field21: getRandomValueForField('String'),
    field22: getRandomValueForField('bool'),
    field23: getRandomValueForField('bool'),
    field24: getRandomValueForField('String'),
    field25: getRandomValueForField('DateTime'),
    field26: getRandomValueForField('String'),
    field27: getRandomValueForField('Map<String, String>'),
    field28: getRandomValueForField('String'),
    field29: getRandomValueForField('List<int>'),
    field30: getRandomValueForField('Map<String,int>'),
    field31: getRandomValueForField('bool'),
    field32: getRandomValueForField('List<String>'),
    field33: getRandomValueForField('Map<String,int>'),
    field34: getRandomValueForField('List<int>'),
    field35: getRandomValueForField('double'),
    field36: getRandomValueForField('List<String>'),
    field37: getRandomValueForField('Map<String, String>'),
    field38: getRandomValueForField('bool'),
    field39: getRandomValueForField('int'),
    field40: getRandomValueForField('List<int>'),
    field41: getRandomValueForField('Map<String, String>'),
    field42: getRandomValueForField('DateTime'),
    field43: getRandomValueForField('int'),
    field44: getRandomValueForField('List<String>'),
    field45: getRandomValueForField('bool'),
    field46: getRandomValueForField('DateTime'),
    field47: getRandomValueForField('List<int>'),
    field48: getRandomValueForField('List<String>'),
    field49: getRandomValueForField('int'),
    model: model4,
  );
  models.add(model5);
  var model6 = Model6(
    field0: getRandomValueForField('int'),
    field1: getRandomValueForField('DateTime'),
    field2: getRandomValueForField('bool'),
    field3: getRandomValueForField('List<String>'),
    field4: getRandomValueForField('bool'),
    field5: getRandomValueForField('Map<String, String>'),
    field6: getRandomValueForField('List<int>'),
    field7: getRandomValueForField('List<String>'),
    field8: getRandomValueForField('List<String>'),
    field9: getRandomValueForField('Map<String, String>'),
    field10: getRandomValueForField('DateTime'),
    field11: getRandomValueForField('Map<String,int>'),
    field12: getRandomValueForField('double'),
    field13: getRandomValueForField('Map<String,int>'),
    field14: getRandomValueForField('Map<String,int>'),
    field15: getRandomValueForField('bool'),
    field16: getRandomValueForField('List<String>'),
    field17: getRandomValueForField('String'),
    field18: getRandomValueForField('List<int>'),
    field19: getRandomValueForField('List<int>'),
    field20: getRandomValueForField('double'),
    field21: getRandomValueForField('Map<String,int>'),
    field22: getRandomValueForField('Map<String, String>'),
    field23: getRandomValueForField('double'),
    field24: getRandomValueForField('DateTime'),
    field25: getRandomValueForField('List<int>'),
    field26: getRandomValueForField('double'),
    field27: getRandomValueForField('Map<String, String>'),
    field28: getRandomValueForField('DateTime'),
    field29: getRandomValueForField('Map<String, String>'),
    field30: getRandomValueForField('Map<String, String>'),
    field31: getRandomValueForField('Map<String,int>'),
    field32: getRandomValueForField('List<int>'),
    field33: getRandomValueForField('List<int>'),
    field34: getRandomValueForField('String'),
    field35: getRandomValueForField('Map<String,int>'),
    field36: getRandomValueForField('List<int>'),
    field37: getRandomValueForField('List<int>'),
    field38: getRandomValueForField('List<int>'),
    field39: getRandomValueForField('Map<String,int>'),
    field40: getRandomValueForField('bool'),
    field41: getRandomValueForField('List<String>'),
    field42: getRandomValueForField('DateTime'),
    field43: getRandomValueForField('DateTime'),
    field44: getRandomValueForField('Map<String, String>'),
    field45: getRandomValueForField('List<int>'),
    field46: getRandomValueForField('Map<String,int>'),
    field47: getRandomValueForField('List<String>'),
    field48: getRandomValueForField('double'),
    field49: getRandomValueForField('Map<String,int>'),
    model: model5,
  );
  models.add(model6);
  var model7 = Model7(
    field0: getRandomValueForField('bool'),
    field1: getRandomValueForField('List<String>'),
    field2: getRandomValueForField('DateTime'),
    field3: getRandomValueForField('List<String>'),
    field4: getRandomValueForField('List<int>'),
    field5: getRandomValueForField('String'),
    field6: getRandomValueForField('DateTime'),
    field7: getRandomValueForField('List<int>'),
    field8: getRandomValueForField('bool'),
    field9: getRandomValueForField('int'),
    field10: getRandomValueForField('DateTime'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('double'),
    field13: getRandomValueForField('DateTime'),
    field14: getRandomValueForField('int'),
    field15: getRandomValueForField('String'),
    field16: getRandomValueForField('Map<String, String>'),
    field17: getRandomValueForField('List<int>'),
    field18: getRandomValueForField('double'),
    field19: getRandomValueForField('List<int>'),
    field20: getRandomValueForField('List<String>'),
    field21: getRandomValueForField('List<int>'),
    field22: getRandomValueForField('Map<String,int>'),
    field23: getRandomValueForField('DateTime'),
    field24: getRandomValueForField('String'),
    field25: getRandomValueForField('Map<String, String>'),
    field26: getRandomValueForField('List<String>'),
    field27: getRandomValueForField('String'),
    field28: getRandomValueForField('bool'),
    field29: getRandomValueForField('List<int>'),
    field30: getRandomValueForField('bool'),
    field31: getRandomValueForField('Map<String,int>'),
    field32: getRandomValueForField('double'),
    field33: getRandomValueForField('Map<String, String>'),
    field34: getRandomValueForField('List<int>'),
    field35: getRandomValueForField('DateTime'),
    field36: getRandomValueForField('Map<String,int>'),
    field37: getRandomValueForField('int'),
    field38: getRandomValueForField('List<int>'),
    field39: getRandomValueForField('bool'),
    field40: getRandomValueForField('String'),
    field41: getRandomValueForField('DateTime'),
    field42: getRandomValueForField('List<int>'),
    field43: getRandomValueForField('List<String>'),
    field44: getRandomValueForField('Map<String,int>'),
    field45: getRandomValueForField('List<String>'),
    field46: getRandomValueForField('String'),
    field47: getRandomValueForField('List<String>'),
    field48: getRandomValueForField('DateTime'),
    field49: getRandomValueForField('int'),
    model: model6,
  );
  models.add(model7);
  var model8 = Model8(
    field0: getRandomValueForField('bool'),
    field1: getRandomValueForField('List<String>'),
    field2: getRandomValueForField('DateTime'),
    field3: getRandomValueForField('List<String>'),
    field4: getRandomValueForField('List<int>'),
    field5: getRandomValueForField('String'),
    field6: getRandomValueForField('DateTime'),
    field7: getRandomValueForField('List<int>'),
    field8: getRandomValueForField('bool'),
    field9: getRandomValueForField('int'),
    field10: getRandomValueForField('DateTime'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('double'),
    field13: getRandomValueForField('DateTime'),
    field14: getRandomValueForField('int'),
    field15: getRandomValueForField('String'),
    field16: getRandomValueForField('Map<String, String>'),
    field17: getRandomValueForField('List<int>'),
    field18: getRandomValueForField('double'),
    field19: getRandomValueForField('List<int>'),
    field20: getRandomValueForField('List<String>'),
    field21: getRandomValueForField('List<int>'),
    field22: getRandomValueForField('Map<String,int>'),
    field23: getRandomValueForField('DateTime'),
    field24: getRandomValueForField('String'),
    field25: getRandomValueForField('Map<String, String>'),
    field26: getRandomValueForField('List<String>'),
    field27: getRandomValueForField('String'),
    field28: getRandomValueForField('bool'),
    field29: getRandomValueForField('List<int>'),
    field30: getRandomValueForField('bool'),
    field31: getRandomValueForField('Map<String,int>'),
    field32: getRandomValueForField('double'),
    field33: getRandomValueForField('Map<String, String>'),
    field34: getRandomValueForField('List<int>'),
    field35: getRandomValueForField('DateTime'),
    field36: getRandomValueForField('Map<String,int>'),
    field37: getRandomValueForField('int'),
    field38: getRandomValueForField('List<int>'),
    field39: getRandomValueForField('bool'),
    field40: getRandomValueForField('String'),
    field41: getRandomValueForField('DateTime'),
    field42: getRandomValueForField('List<int>'),
    field43: getRandomValueForField('List<String>'),
    field44: getRandomValueForField('Map<String,int>'),
    field45: getRandomValueForField('List<String>'),
    field46: getRandomValueForField('String'),
    field47: getRandomValueForField('List<String>'),
    field48: getRandomValueForField('DateTime'),
    field49: getRandomValueForField('int'),
    model: model7,
  );
  models.add(model8);
  var model9 = Model9(
    field0: getRandomValueForField('bool'),
    field1: getRandomValueForField('List<String>'),
    field2: getRandomValueForField('DateTime'),
    field3: getRandomValueForField('List<String>'),
    field4: getRandomValueForField('List<int>'),
    field5: getRandomValueForField('String'),
    field6: getRandomValueForField('DateTime'),
    field7: getRandomValueForField('List<int>'),
    field8: getRandomValueForField('bool'),
    field9: getRandomValueForField('int'),
    field10: getRandomValueForField('DateTime'),
    field11: getRandomValueForField('int'),
    field12: getRandomValueForField('double'),
    field13: getRandomValueForField('DateTime'),
    field14: getRandomValueForField('int'),
    field15: getRandomValueForField('String'),
    field16: getRandomValueForField('Map<String, String>'),
    field17: getRandomValueForField('List<int>'),
    field18: getRandomValueForField('double'),
    field19: getRandomValueForField('List<int>'),
    field20: getRandomValueForField('List<String>'),
    field21: getRandomValueForField('List<int>'),
    field22: getRandomValueForField('Map<String,int>'),
    field23: getRandomValueForField('DateTime'),
    field24: getRandomValueForField('String'),
    field25: getRandomValueForField('Map<String, String>'),
    field26: getRandomValueForField('List<String>'),
    field27: getRandomValueForField('String'),
    field28: getRandomValueForField('bool'),
    field29: getRandomValueForField('List<int>'),
    field30: getRandomValueForField('bool'),
    field31: getRandomValueForField('Map<String,int>'),
    field32: getRandomValueForField('double'),
    field33: getRandomValueForField('Map<String, String>'),
    field34: getRandomValueForField('List<int>'),
    field35: getRandomValueForField('DateTime'),
    field36: getRandomValueForField('Map<String,int>'),
    field37: getRandomValueForField('int'),
    field38: getRandomValueForField('List<int>'),
    field39: getRandomValueForField('bool'),
    field40: getRandomValueForField('String'),
    field41: getRandomValueForField('DateTime'),
    field42: getRandomValueForField('List<int>'),
    field43: getRandomValueForField('List<String>'),
    field44: getRandomValueForField('Map<String,int>'),
    field45: getRandomValueForField('List<String>'),
    field46: getRandomValueForField('String'),
    field47: getRandomValueForField('List<String>'),
    field48: getRandomValueForField('DateTime'),
    field49: getRandomValueForField('int'),
    model: model8,
  );
  models.add(model9);
  return models;
}


class ModelViewer extends StatelessWidget {
  final List<dynamic> models;

  const ModelViewer({super.key, required this.models});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Model Viewer'),
      ),
      body: ListView.builder(
        itemCount: models.length,
        itemBuilder: (context, index) {
          final model = models[index];
          return ListTile(
            title: Text(model.runtimeType.toString()),
            subtitle: Text(
              // Display the first 3 fields (or less if there are fewer)
              model.toString(),
            ),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) =>
                      DetailPage(model: model), // Pass the model
                ),
              );
            },
          );
        },
      ),
    );
  }
}

class DetailPage extends StatelessWidget {
  final dynamic model;

  const DetailPage({super.key, required this.model});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Detail View - ${model.runtimeType}'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Text(model.toString()), // Display all fields
      ),
    );
  }
}

void main() {
  final models = getModels();
  runApp(MaterialApp(
    home: ModelViewer(models: models),
  ));
}
